-- MySQL Script generated by MySQL Workbench
-- Wed Oct 12 16:52:43 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`kontrahent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kontrahent` (
  `idkontrahenta` INT(20) NOT NULL,
  `imie` VARCHAR(20) NOT NULL,
  `nazwisko` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idkontrahenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`firma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`firma` (
  `dzial` INT NOT NULL,
  `nazwa` VARCHAR(45) NULL,
  `adres` VARCHAR(50) NULL,
  PRIMARY KEY (`dzial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pracownik` (
  `idpracownika` INT NOT NULL,
  `imie` VARCHAR(20) NOT NULL,
  `nazwisko` VARCHAR(20) NOT NULL,
  `adres` VARCHAR(45) NOT NULL,
  `zarobki` FLOAT(7,2) NOT NULL,
  `telefon` VARCHAR(45) NULL,
  `data_ur` VARCHAR(45) NULL,
  `pesel` CHAR(11) NULL,
  `dzial` INT NOT NULL,
  PRIMARY KEY (`dzial`, `zarobki`),
  INDEX `fk_pracownik_firma1_idx` (`dzial` ASC) VISIBLE,
  CONSTRAINT `fk_pracownik_firma1`
    FOREIGN KEY (`dzial`)
    REFERENCES `mydb`.`firma` (`dzial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `nazwa` VARCHAR(20) NOT NULL,
  `data` DATE NULL,
  `miejsce` VARCHAR(45) NULL,
  `typ_dokumentu` VARCHAR(7) NULL,
  `przychód` VARCHAR(45) NULL,
  `koszty` VARCHAR(45) NOT NULL,
  `odwolanie` TINYINT NULL,
  `idkontrahenta` INT(20) NOT NULL,
  PRIMARY KEY (`idkontrahenta`, `koszty`),
  CONSTRAINT `fk_event_kontrahent`
    FOREIGN KEY (`idkontrahenta`)
    REFERENCES `mydb`.`kontrahent` (`idkontrahenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rozliczenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rozliczenia` (
  `id_dostawcy` INT NOT NULL,
  `id_odbiorcy` VARCHAR(45) NOT NULL,
  `koszty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`koszty`),
  CONSTRAINT `fk_rozliczenia_event1`
    FOREIGN KEY (`koszty`)
    REFERENCES `mydb`.`event` (`koszty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bilans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bilans` (
  `zarobki` FLOAT(7,2) NOT NULL,
  `roczny` BIGINT(6) NULL,
  `kwartalny` BIGINT(5) NULL,
  `zarobki` FLOAT(7,2) NOT NULL,
  `koszty` TINYINT(10) NOT NULL,
  PRIMARY KEY (`zarobki`, `koszty`),
  INDEX `fk_bilans_event1_idx` (`koszty` ASC) VISIBLE,
  CONSTRAINT `fk_bilans_pracownik1`
    FOREIGN KEY (`zarobki`)
    REFERENCES `mydb`.`pracownik` (`zarobki`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bilans_event1`
    FOREIGN KEY (`koszty`)
    REFERENCES `mydb`.`event` (`koszty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
